# docker compose build - используем эту команду, если меняли что-то в Dockerfile
# docker compose up - если изменили только docker-compose


services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6398

  tip_top:
    image: image
    restart: always
    build:
      context: .
    container_name: app
    env_file:
      - .env-non-dev
    depends_on: # Запускаем только после запуска БД и Redis (depends on = зависит от)
#      - db
      - redis
    ports:
      - 8888:8000

